# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.73.0
    hooks:
    - id: terraform_fmt
    - id: terraform_docs
    #  - id: terraform_tflint
    # - id: terraform_validate
    # - id: terraform_tfsec
    # - id: checkov
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.3.0
  #   hooks:
  #     - id: check-merge-conflict
  #     - id: trailing-whitespace
  #     - id: check-yaml
  #     - id: check-added-large-files
  #     - id: detect-private-key
  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: v0.9.0
  #   hooks:
  #     - id: markdownlint
  # - repo: https://github.com/ansible-community/ansible-lint
  #   rev: v5.0.11
  #   hooks:
  #     - id: ansible-lint