#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: scenarios-200

on:

  pull_request:
  #   branches:
  #     - master
  #     - '2010.0.0'
  push:
    paths-ignore:
      - .github/workflows/master-100.yaml
      - 'documentation/**'
      - '_pictures/**'
      - 'README.md'
      - 'CHANGELOG.md'
  schedule:
    - cron:  '0 0 * * *'

env:
  TF_CLI_ARGS: '-no-color'
  TF_CLI_ARGS_destroy: '-auto-approve -refresh=false'
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  foundations:
    name: foundations
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
          random_length: ['5']

    container:
      image: aztfmod/roverdev:2010.141511
      options: --user 0

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: Azure/caf-terraform-landingzones
          path: public
          ref: "2010.0.0"

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"

      - name: launchpad
        run: |
          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/public/landingzones/caf_launchpad -a apply \
            -level level0 \
            -var-folder ${GITHUB_WORKSPACE}/public/landingzones/caf_launchpad/scenario/200 \
            -launchpad \
            -parallelism=30 \
            --environment ${{ github.run_id }} \
            '-var random_length=${{ matrix.random_length }}' \
            '-var prefix=g${{ github.run_id }}' \\
            '-var tags={testing_job_id="${{ github.run_id }}"}'


      - name: foundations
        run: |
          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/public/landingzones/caf_foundations -a apply \
            -level level1 \
            --environment ${{ github.run_id }}

  examples:
    name: examples
    runs-on: ubuntu-latest

    needs: foundations

    strategy:
      fail-fast: false
      matrix:
          config_files: [
            "examples/mssql_server/200-mssql",
            "examples/mssql_server/200-mssql-two-regions"
          ]

    container:
      image: aztfmod/roverdev:2010.141511
      options: --user 0

    steps:
      - uses: actions/checkout@v2

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: deploy example
        run: |
          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/examples -a apply \
            -level level2 \
            -tfstate $(basename ${{ matrix.config_files }}).tfstate \
            -var-file ${GITHUB_WORKSPACE}/${{ matrix.config_files }}.tfvars \
            --environment ${{ github.run_id }}

      - name: destroy example
        if: always()
        run: |
          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/examples -a destroy \
            -level level2 \
            -tfstate $(basename ${{ matrix.config_files }}).tfstate \
            -var-file ${GITHUB_WORKSPACE}/${{ matrix.config_files }}.tfvars \
            --environment ${{ github.run_id }} \
            -refresh=false \
            -auto-approve

  foundations_destroy:
    name: foundations_destroy
    runs-on: ubuntu-latest
    if: always()
    needs: examples

    strategy:
      fail-fast: false

    container:
      image: aztfmod/roverdev:2010.141511
      options: --user 0

    steps:
      - uses: actions/checkout@v2
        with:
          repository: Azure/caf-terraform-landingzones
          path: public
          ref: "2010.0.0"

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"


      - name: foundations
        run: |
          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/public/landingzones/caf_foundations -a destroy \
            -level level1 \
            -parallelism=30 \
            --environment ${{ github.run_id }} \
            -auto-approve

      - name: Remove launchpad
        run: |

          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/public/landingzones/caf_launchpad/ -a destroy \
            -level level0 \
            -var-folder ${GITHUB_WORKSPACE}/public/landingzones/caf_launchpad/scenario/200 \
            -launchpad \
            -parallelism=30 \
            -env ${{ github.run_id }} \
            '-var prefix=g${{ github.run_id }}' \
            '-var tags={testing_job_id="${{ github.run_id }}"}' \
            -auto-approve


      - name: Complete purge
        if: ${{ always() }}
        run: |
          for i in `az monitor diagnostic-settings subscription list -o tsv --query "value[?contains(name, '${{ github.run_id }}' )].name"`; do echo "purging subscription diagnostic-settings: $i" && $(az monitor diagnostic-settings subscription delete --name $i --yes); done
          for i in `az monitor log-profiles list -o tsv --query '[].name'`; do az monitor log-profiles delete --name $i; done
          for i in `az ad group list --query "[?contains(displayName, '${{ github.run_id }}')].objectId" -o tsv`; do echo "purging Azure AD group: $i" && $(az ad group delete --verbose --group $i || true); done
          for i in `az ad app list --query "[?contains(displayName, '${{ github.run_id }}')].appId" -o tsv`; do echo "purging Azure AD app: $i" && $(az ad app delete --verbose --id $i || true); done
          for i in `az keyvault list-deleted --query "[?tags.environment=='${{ github.run_id }}'].name" -o tsv`; do az keyvault purge --name $i; done
          for i in `az group list --query "[?tags.environment=='${{ github.run_id }}'].name" -o tsv`; do echo "purging resource group: $i" && $(az group delete -n $i -y --no-wait || true); done
          for i in `az role assignment list --query "[?contains(roleDefinitionName, '${{ github.run_id }}')].roleDefinitionName" -o tsv`; do echo "purging role assignment: $i" && $(az role assignment delete --role $i || true); done
          for i in `az role definition list --query "[?contains(roleName, '${{ github.run_id }}')].roleName" -o tsv`; do echo "purging custom role definition: $i" && $(az role definition delete --name $i || true); done