#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: scenario-100

on:
  pull_request:
    branches:
      - master
  # push:
  #   branches:
  #     - master
  #   paths-ignore:
  #     - .github/workflows/master-200.yaml
  #     - 'documentation/**'
  #     - '_pictures/**'
  #     - 'README.md'
  #     - 'CHANGELOG.md'
  schedule:
    - cron:  '0 3 * * *'

env:
  TF_CLI_ARGS: '-no-color'
  TF_CLI_ARGS_destroy: '-auto-approve -refresh=false'
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  foundations:
    name: foundations
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
          region: ["southeastasia"]
          convention: ["cafrandom"]

    container:
      image: aztfmod/roveralpha:2009.030225
      options: --user 0

    steps:
      - uses: actions/checkout@v2

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"

      - name: launchpad
        run: |
          # ln -s ${GITHUB_WORKSPACE} /tf/caf

          # ls /tf/caf

          id=$(az storage account list --query "[?tags.tfstate=='level0' && tags.environment=='${{ github.run_id }}']" -o json | jq -r .[0].id)

          if [ "${id}" == "null" ]; then

            /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/landingzones/caf_launchpad -a apply \
              -var-file ${GITHUB_WORKSPACE}/landingzones/caf_launchpad/scenario/100/ci-configuration.tfvars \
              -launchpad \
              --environment ${{ github.run_id }} \
              '-var prefix=g${{ github.run_id }}' \
              '-var regions={region1="${{ matrix.region }}"}' \
              '-var convention=${{ matrix.convention }}' \
              '-var tags={testing_job_id="${{ github.run_id }}"}'
          fi

      - name: foundations
        run: |
          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/landingzones/caf_foundations -a apply \
          --environment ${{ github.run_id }}

  examples:
    name: examples
    runs-on: ubuntu-latest

    needs: foundations

    strategy:
      fail-fast: false
      matrix:
          config_files: [
            "webapps/appservice/appservice-simple",
            "webapps/appservice/appservice-slots"
          ]
          convention: ["random"]

    container:
      image: aztfmod/roveralpha:2009.030225
      options: --user 0

    steps:
      - uses: actions/checkout@v2

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: deploy example
        run: |
          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/examples -a apply \
            -tfstate $(basename ${{ matrix.config_files }}).tfstate \
            -var-file ${GITHUB_WORKSPACE}/examples/${{ matrix.config_files }}.tfvars \
            --environment ${{ github.run_id }}

      - name: destroy example
        run: |
          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/examples -a destroy \
            -tfstate $(basename ${{ matrix.config_files }}).tfstate \
            -var-file ${GITHUB_WORKSPACE}/examples/${{ matrix.config_files }}.tfvars \
            --environment ${{ github.run_id }} \
            -auto-approve

  # landingzones:
  #   name: landingzones
  #   runs-on: ubuntu-latest

  #   needs: [level0, caf_foundations]

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #         landingzone: ["landingzone_hub_spoke", "landingzone_secure_vnet_dmz", "landingzone_starter", "landingzone_vdc_demo", "landingzone_hub_mesh"]
  #         region: ["westus2"]
  #         convention: ["cafrandom"]
  #         environment: ["integration-tests"]

  #   container:
  #     image: aztfmod/rover:2007.2409
  #     options: --user 0

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name:  setup context
  #       id: context
  #       run: |
  #         ln -s ${GITHUB_WORKSPACE} /tf/caf
  #         echo "ls /tf/caf" && ls -lsa /tf/caf
  #         ls -lsa /tmp

  #     - name: Login azure
  #       run: |
  #         az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
  #         az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

  #         echo "local user: $(whoami)"

  #     - name: deploy landing_zone
  #       run: |
  #         /tf/rover/rover.sh -lz /tf/caf/caf-terraform-landingzones/landingzones/${{ matrix.landingzone }} -a apply \
  #           -env ${{ github.run_id }} \
  #           '-var tags={testing_job_id="${{ github.run_id }}"}' \
  #           '-var-file ${{ env.TFVARS_PATH }}/${{ matrix.environment }}/${{ matrix.landingzone }}/${{ matrix.landingzone }}.tfvars'

  #     - name: destroy landing_zone
  #       if: always()
  #       run: |
  #         /tf/rover/rover.sh -lz /tf/caf/caf-terraform-landingzones/landingzones/${{ matrix.landingzone }} -a destroy \
  #           --environment ${{ github.run_id }} \
  #           '-var tags={testing_job_id="${{ github.run_id }}"}' \
  #           '-var-file ${{ env.TFVARS_PATH }}/${{ matrix.environment }}/${{ matrix.landingzone }}/${{ matrix.landingzone }}.tfvars'

  # caf_foundations_destroy:
  #   name: caf_foundations_destroy
  #   runs-on: ubuntu-latest
  #   if: always()
  #   needs: landingzones

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #         landingzone: ["landingzone_caf_foundations"]
  #         region: ["westus2"]
  #         convention: ["random"]
  #         environment: ["integration-tests"]

  #   container:
  #     image: aztfmod/rover:2007.2409
  #     options: --user 0

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name:  setup context
  #       id: context
  #       run: |
  #         ln -s ${GITHUB_WORKSPACE} /tf/caf
  #         echo "ls /tf/caf" && ls -lsa /tf/caf
  #         ls -lsa /tmp

  #         # workspace='caffoundationsci'
  #         # echo ::set-env name=TF_VAR_workspace::${workspace}

  #     - name: Login azure
  #       run: |
  #         az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
  #         az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

  #         echo "local user: $(whoami)"

  #     - name: destroy caf_foundations
  #       run: |
  #         /tf/rover/rover.sh -lz /tf/caf/caf-terraform-landingzones/landingzones/${{ matrix.landingzone }} -a destroy \
  #           --environment ${{ github.run_id }} \
  #           -var prefix=g${{ github.run_id}} \
  #           '-var tags={testing_job_id="${{ github.run_id }}"}' \
  #           '-var-file ${{ env.TFVARS_PATH }}/${{ matrix.environment }}/${{ matrix.landingzone }}/${{ matrix.landingzone }}_${{ matrix.region }}_${{ matrix.convention }}.tfvars' \
  #           '-auto-approve'

  foundations_destroy:
    name: foundations_destroy
    runs-on: ubuntu-latest
    if: always()
    needs: examples

    strategy:
      fail-fast: false
      matrix:
          region: ["westus2"]
          convention: ["cafrandom"]

    container:
      image: aztfmod/roveralpha:2009.030225
      options: --user 0

    steps:
      - uses: actions/checkout@v2

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"


      - name: foundations
        run: |
          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/landingzones/caf_foundations -a destroy \
          --environment ${{ github.run_id }} \
          -auto-approve

      - name: Remove launchpad
        run: |

          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/landingzones/caf_launchpad/ -a destroy \
            -var-file ${GITHUB_WORKSPACE}/landingzones/caf_launchpad/scenario/100/ci-configuration.tfvars \
            -launchpad \
            --environment ${{ github.run_id }} \
            '-var prefix=g${{ github.run_id }}' \
            '-var regions={region1="${{ matrix.region }}"}' \
            '-var convention=${{ matrix.convention }}' \
            '-var tags={testing_job_id="${{ github.run_id }}"}' \
            -auto-approve


      - name: Complete purge
        if: ${{ always() }}
        run: |
          for i in `az monitor log-profiles list -o tsv --query '[].name'`; do az monitor log-profiles delete --name $i; done
          for i in `az ad group list --query "[?contains(displayName, '${{ github.run_id }}')].objectId" -o tsv`; do echo "purging Azure AD group: $i" && $(az ad group delete --verbose --group $i || true); done
          for i in `az ad app list --query "[?contains(displayName, '${{ github.run_id }}')].appId" -o tsv`; do echo "purging Azure AD app: $i" && $(az ad app delete --verbose --id $i || true); done
          for i in `az group list --query "[?tags.environment=='${{ github.run_id }}'].name" -o tsv`; do echo "purging resource group: $i" && $(az group delete -n $i -y --no-wait || true); done
          for i in `az role assignment list --query "[?contains(roleDefinitionName, '${{ github.run_id }}')].roleDefinitionName" -o tsv`; do echo "purging role assignment: $i" && $(az role assignment delete --role $i || true); done
          for i in `az role definition list --query "[?contains(roleName, '${{ github.run_id }}')].roleName" -o tsv`; do echo "purging custom role definition: $i" && $(az role definition delete --name $i || true); done